api:
  port: 7205
mongodb:
  url: 'mongodb://127.0.0.1:27017/chat-app'
JWT_SECRET: oijsdfogij02349sdpok
TEST_SOCKET_SECRET: 'd0934i2*@!*%j4fehg0[]sdf,af2'
https:
  enable: false
  cert: null
  key: null
auth:
  token_expires_in: 120
default_server_id: ''
